### ISSUE TITLE
Feat: 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by dogmania** [Kusitms-FITPET-DEV/FITPET_Android#1]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

프로젝트 초기 세팅

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 외부 라이브러리 의존성 설정
- [x] BaseFragment, BaseActivity, BaseViewModel 구현
- [x] Application 클래스 구현
- [x] Event, PageState 구현
- [x] navigation 구현
- [x] 네트워크 설정
- [x] DataStore 설정
