### ISSUE TITLE
Feat: 마이펫 등록 - 반려동물 이름 입력 페이지 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-FITPET-DEV/FITPET_Android#15]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

마이펫 등록 - 반려동물 이름 입력 페이지 구현

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] PetNameInputFragment, ViewModel, PageState, Event 구현
- [x] 카카오 로그인 이후 PetNameInputFragment로 이동
- [x] 한 글자 이상 입력하면 경고 문구 색상 파란색으로 변경
- [x] 디자인 시스템 변경
- [x] Point Blue 색상 변경
