### ISSUE TITLE
Feat: 품종 선택 페이지 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-FITPET-DEV/FITPET_Android#17]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

- 품종 선택 페이지 구현

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] PetBreedFragment, ViewModel, Event, PageState 구현
- [x] PetNameInputFragment -> PetBreedFragment 내비게이션 연결
- [x] PetNameInputFragment 백그라운드 색상 변경
- [x] PetNameInputFragment Hint 텍스트 추가
