### ISSUE TITLE
FEAT: 보험금 청구(1/5) 화면

### ISSUE THREAD

**Issue by emjayMJkim** [Kusitms-FITPET-DEV/FITPET_Android#28]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

보험금 청구(1/5) 화면

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 보험금 청구 원인 선택 로직 구현
- [x] 캘린더 날짜 선택 구현
- [x] 원인 및 날짜 모든 입력 완료 시 버튼 활성화 로직 구현
- [x] 버튼 활성화 시 보험금 청구(2/5) 이동 
- [x] 캘린더 정확한 날짜 구현
