### ISSUE TITLE
Feat: 건너뛰기 다이얼로그 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-FITPET-DEV/FITPET_Android#30]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

- 건너뛰기 바텀시트 구현
- 다음 버튼 예외처리

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] SkipDialog 구현
- [x] 다음 버튼 예외처리
- [x] 온보딩 터치 영역 수정
- [x] 온보딩 아이콘 수정
