### ISSUE TITLE
Feat: 보험금 청구(2/5) 화면 

### ISSUE THREAD

**Issue by emjayMJkim** [Kusitms-FITPET-DEV/FITPET_Android#34]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

Feat: 보험금 청구(2/5) 화면 

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 보험금 청구 화면 구현
- [x] 사진 찍기 연동
- [x] 사진 보관함(갤러리) 연동 
- [x] 사진 추가 및 삭제 로직 구현 
- [x] 버튼 활성화 및 페이지(3/5) 이동
