### ISSUE TITLE
Feat: 카카오 로그인 API 연결

### ISSUE THREAD

**Issue by dogmania** [Kusitms-FITPET-DEV/FITPET_Android#38]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

- 카카오 로그인 API 연결
- 스플래시 영상 삽입

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 스플래시 영상 삽입
- [x] 카카오 로그인 버튼 디자인 수정
- [x] 펫 등록 버튼 텍스트 색상 수정
- [x] BaseViewModel 로직 수정
- [x] AuthRepository, AuthRepositoryImpl 구현
- [x] AuthService 구현
- [x] TokenProvider 구현
- [x] 건너뛰기 메인 화면 연결
