### ISSUE TITLE
Feat: 보험금 청구(3/5) 화면

### ISSUE THREAD

**Issue by emjayMJkim** [Kusitms-FITPET-DEV/FITPET_Android#40]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

보험금 청구(3/5) 화면 구현

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 계좌 입력 화면 구현
- [x] 예금주 및 계좌 입력 구현
- [x] 은행 드롭다운
- [x] 모두 입력 완료 시 버튼 활성화 및 페이지 이동
