### ISSUE TITLE
Feat: 보험금 청구(4/5) 화면

### ISSUE THREAD

**Issue by emjayMJkim** [Kusitms-FITPET-DEV/FITPET_Android#42]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

보험금 청구(4/5) 화면 구현

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 연락 수단(카카오/이메일) 체크박스
- [x] 이메일 입력
- [x] 연락 수단 입력 페이지 버튼 활성화 로직
- [x] 동의 안내 바텀시트
- [x] 동의 버튼 활성화 로직(필수/선택)
- [x] 버튼 활성화 시 청구 내용 확인 페이지 이동
