### ISSUE TITLE
Feat: 마이펫 등록 API 연결

### ISSUE THREAD

**Issue by dogmania** [Kusitms-FITPET-DEV/FITPET_Android#51]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

- 마이펫 등록 API 연결

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 입력 데이터 내비게이션으로 넘기기
- [x] 마이펫 등록 API 연결
- [x] 자동완성 드롭다운 메뉴 디자인 변경
- [x] 입력한 단어의 색 변경
- [x] 출생년도 예외처리
