### ISSUE TITLE
Feat: 알림 화면 구현 

### ISSUE THREAD

**Issue by emjayMJkim** [Kusitms-FITPET-DEV/FITPET_Android#69]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

알림 화면 구현 

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] 알림 화면 구현
- [x] 보상 변경 내역 조회 API 연결
- [x] 보상 내역 확인 여부 변경 API 연결
