### ISSUE TITLE
Feat: BaseViewModel 로직 변경, Splash 완성, ResourceProvider 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-FITPET-DEV/FITPET_Android#8]
## Description
> 어떤 작업에 대한 이슈인지 적어주세요. ex) 프로젝트 초기 세팅

BaseViewModel 로직 변경, Splash 완성, ResourceProvider 구현

## TODO
> 이슈에서 해야 할 일을 적어주세요.

- [x] BaseViewModel 수정
- [x] Splash 1.5초 렌더링 후 온보딩으로 이동할 수 있도록 코드 수정
- [x] Splash 임시 png 아이콘 추가
- [x] ViewModel에서 string.xml과 같은 리소스 파일에서 데이터를 가져올 수 있도록 ResourceProvider 구현
